services:
  car:
    image: buettner123/producer
    build:
      context: .
    environment:
      - NODE_ENV=car
    volumes:
      - ./src/:/usr/src/app/src/ #TODO: remove volume, dev only
      - ./config/:/usr/src/app/config/
    networks:
      - kafka-proxy

networks:
  kafka-proxy:
    name: kafka
