services:
  car:
    image: buettner123/producer
    build:
      context: .
    environment:
      - NODE_ENV=car
    volumes:
      - ./config/:/usr/src/app/config/
    networks:
      - kafka-proxy
  bike:
    image: buettner123/producer
    build:
      context: .
    environment:
      - NODE_ENV=bike
    volumes:
      - ./config/:/usr/src/app/config/
    networks:
      - kafka-proxy
  pedestrian:
    image: buettner123/producer
    build:
      context: .
    environment:
      - NODE_ENV=pedestrian
    volumes:
      - ./config/:/usr/src/app/config/
    networks:
      - kafka-proxy

networks:
  kafka-proxy:
    name: kafka
